name: democomp

services:
  app:
    build: ./app
    environment:
      NODE_PORT: "3456"
    networks:
      - demonet

  entry:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./prx/demoapp.conf:/etc/nginx/conf.d/demoapp.conf:ro
    ports:
      - "5678:6789"    # exp√µe para o host
    networks:
      - demonet

  monitor:
    image: alpine:latest
    tty: true
    depends_on:
      - entry
    networks:
      - demonet

networks:
  demonet: {}

